onboarding = false
switch_ascii_input_source_in_prefix = true

[keys]
prefix = "ctrl+q"
split_horizontal = "prefix+minus"
split_vertical = 'prefix+\'
open_notification_target = "prefix+o"

[ui.toast]
delivery = "herdr"

[ui.sound]
enabled = false
