[settings]
idiomatic_version_file_enable_tools = ["python"]
trusted_config_paths = [
  "~/ghq/github.com/kawagh",
  "~/.herdr/worktrees",
]

[tools]
"aqua:go-task/task" = "latest"
"github:Genymobile/scrcpy" = { version = "4.1", extract_all = true, bin_path = "." }
fzf = "latest"
hadolint = "latest"
node = "latest"
